services:
  app:
    build: .
    container_name: chefsatlas_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: chefsatlas
      DB_USERNAME: chefsatlas_user
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: chefsatlas_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chefsatlas
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: chefsatlas_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20


volumes:
  db_data:
    driver: local
